 export const OTHERLANG_GRID = [
       {
        key:3,
        topic:"R",
        color:"#96d4d4"
       },
       {
        key:4,
        topic:"Kotlin",
        color:"#ffc0c7"
       },
       {
        key:5,
        topic:"Node.js",
        color:"#d9eee1"
       },
       {
        key:6,
        topic:"React",
        color:"#96d4d4"
       },
       {
        key:7,
        topic:"JSON",
        color:"#fff4a3"
       },
       {
        key:8,
        topic:"Vue",
        color:"#96d4d4"
       },
       {
        key:9,
        topic:"MySQL",
        color:"#ffc0c7"
       },
       {
        key:10,
        topic:"XML",
        color:"#d9eee1"
       },
       {
        key:11,
        topic:"SASS",
        color:"#e7e9eb"
       },
       {
        key:12,
        topic:"Icons",
        color:"#fff4a3"
       },
       {
        key:13,
        topic:"RwD",
        color:"#96d4d4"
       },
       {
        key:14,
        topic:"Graphics",
        color:"#ffc0c7"
       },
       {
        key:15,
        topic:"Svg",
        color:"#d9eee1"
       },
       {
        key:16,
        topic:"Canvas",
        color:"#e7e9eb"
       },
       {
        key:17,
        topic:"RaperryPi",
        color:"#fff4a3"
       },
       {
        key:18,
        topic:'CyberSecurity',
        color:"#96d4d4"
       },
       {
        key:19,
        topic:"Mongo DB",
        color:"#96d4d4"
       },
       {
        key:20,
        topic:"Typescript",
        color:"#d9eee1"
       },
       {
        key:21,
        topic:"Django",
        color:"#e7e9eb"
       },
       {
        key:22,
        topic:"Go",
        color:"#fff4a3"
       },

    

    ]